[package]
name = "gribbrs"
version = "0.1.0"
authors = ["Justin Dennison <justin1dennison@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
