use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum OriginatingCenter {
    Melbourne,
    Moscow,
    UsNationalWeatherServiceNcep,
    UsNationalWeatherServiceNwstg,
    UsNationalWeatherServiceOther,
    Cairo,
    Dakar,
    Nairobi,
    Casablanca,
    Tunis,
    TunisCasablanca,
    LasPalmas,
    Algiers,
    Acmad,
    Mozambique,
    Pretoria,
    LaReunion,
    Khabarovsk,
    NewDelhi,
    Novosibirsk,
    Tashkent,
    Jeddah,
    TokyoJapaneseMeteorologicalAgency,
    Bankok,
    UlanBator,
    Beijing,
    Seoul,
    BuenosAires,
    Brasilia,
    Santiago,
    BrazilianSpaceAgencyInpe,
    Columbia,
    Ecuador,
    Peru,
    Venezuela,
    Miami,
    MiamiNationalHurricaneCenter,
    CanadianMeteorologicalServiceMontreal,
    SanFrancisco,
    ArincCenter,
    UsAirForceAirForceGlobalWeatherCenter,
    FleetNumericalMeteorologyAndOceanographyCenter,
    TheNoaaForecastSystemsLab,
    NationalCenterForAtmosphericResearch,
    ServiceArgosLandover,
    UsNavalOceanographicOffice,
    InternationalResearchInstitudeForClimateAndSociety,
    Honolulu,
    Darwin,
    Reserved,
    Wellington,
    Nadi,
    Singapore,
    Malaysia,
    UKMetOfficeExeter,
    Offenbach,
    Rome,
    Norrkoping,
    FrenchWeatherServiceToulouse,
    Helsinki,
    Belgrade,
    Oslo,
    Prague,
    Episkopi,
    Ankara,
    FrankfurtMain,
    London,
    Copenhagen,
    Rota,
    Athens,
    EuropeanSpaceAgency,
    EuropeanCenterForMediumRangeWeatherForecasts,
    DeBiltNetherlands,
    Brazzaville,
    Abidjan,
    LibyanArabJamahiriya,
    Madagascar,
    Mauritius,
    Niger,
    Seychelles,
    Uganda,
    UnitedRepublicOfTanzania,
    Zimbabwe,
    HongKong,
    Afghanistan,
    Bahrain,
    Bangladesh,
    Bhutan,
    Cambodia,
    DemocraticPeoplesRepublicOfKorea,
    IslamicRepublicOfIran,
    Iraq,
    Kazakhstan,
    Kuwait,
    KyrgyzRepublic,
    LaoPeopleSDemocraticRepublic,
    MacaoChina,
    Maldives,
    Myanmar,
    Nepal,
    Oman,
    Pakistan,
    Qatar,
    Yemen,
    SriLanka,
    Tajikistan,
    Turkmenistan,
    UnitedArabEmirates,
    Uzbekistan,
    VietNam,
    Bolivia,
    Guyana,
    Paraguay,
    Suriname,
    Uruguay,
    FrenchGuyana,
    BrazilianNavyHydrographicCenter,
    NationalCommissionOnSpaceActivitiesArgentina,
    BrazilianDepartmentOfAirspaceControlDecea,
    AntiguaAndBarbuda,
    Bahamas,
    Barbados,
    Belize,
    BritishCaribbeanTerritoriesCenter,
    SanJose,
    Cuba,
    Dominica,
    DominicanRepublic,
    ElSalvador,
    UsNoaaNesdis,
    UsNoaaOfficeOfOceanicAndAtmosphericResearch,
    Guatemala,
    Haiti,
    Honduras,
    Jamaica,
    MexicoCity,
    NetherlandsAntillesAndAruba,
    Nicaragua,
    Panama,
    SaintLucia,
    TrinidadAndTobago,
    FrenchDepartmentsInRaIv,
    UsNationalAeronauticsAndSpaceAdministration,
    IntegratedSystemDataManagementMarineEnvironmentalDataServiceCanada,
    UsCooperativeInstitudeForMeteorologicalSatelliteStudies,
    CookIslands,
    FrenchPolynesia,
    Tonga,
    Vanuatu,
    Brunei,
    Indonesia,
    Kiribati,
    FederatedStatesOfMicronesia,
    NewCaledonia,
    Niue,
    PapuaNewGuinea,
    Philippines,
    Samoa,
    SolomonIslands,
    NationalInstitudeOfWaterAndAtmosphericResearchNewZealand,
    Frascati,
    Lanion,
    Lisbon,
    Reykjavik,
    Madrid,
    Zurich,
    ServiceArgosToulouse,
    Bratislava,
    Budapest,
    Ljubljana,
    Warsaw,
    Zagreb,
    Albania,
    Armenia,
    Austria,
    Azerbaijan,
    Belarus,
    Belgium,
    BosniaAndHerzegovina,
    Bulgaria,
    Cyprus,
    Estonia,
    Georgia,
    Dublin,
    Israel,
    Jordan,
    Latvia,
    Lebanon,
    Lithuania,
    Luxembourg,
    Malta,
    Monaco,
    Romania,
    SyrianArabRepublic,
    TheFormerYugoslavRepublicOfMacedonia,
    Ukraine,
    RepublicOfMoldova,
    OperationalProgrammeForTheExchangeOfWeatherRadarInformationEumetnet,
    ConsortiumForSmallScaleModelling,
    EumetsatOperationsCenter,
    MissingValue,
}

impl From<u16> for OriginatingCenter {
    fn from(n: u16) -> Self {
        match n {
            01 => OriginatingCenter::Melbourne,
            02 => OriginatingCenter::Melbourne,
            03 => OriginatingCenter::Melbourne,
            04 => OriginatingCenter::Moscow,
            05 => OriginatingCenter::Moscow,
            06 => OriginatingCenter::Moscow,
            07 => OriginatingCenter::UsNationalWeatherServiceNcep,
            08 => OriginatingCenter::UsNationalWeatherServiceNwstg,
            09 => OriginatingCenter::UsNationalWeatherServiceOther,
            10 => OriginatingCenter::Cairo,
            11 => OriginatingCenter::Cairo,
            12 => OriginatingCenter::Dakar,
            13 => OriginatingCenter::Dakar,
            14 => OriginatingCenter::Nairobi,
            15 => OriginatingCenter::Nairobi,
            16 => OriginatingCenter::Casablanca,
            17 => OriginatingCenter::Tunis,
            18 => OriginatingCenter::TunisCasablanca,
            19 => OriginatingCenter::TunisCasablanca,
            20 => OriginatingCenter::LasPalmas,
            21 => OriginatingCenter::Algiers,
            22 => OriginatingCenter::Acmad,
            23 => OriginatingCenter::Mozambique,
            24 => OriginatingCenter::Pretoria,
            25 => OriginatingCenter::LaReunion,
            26 => OriginatingCenter::Khabarovsk,
            27 => OriginatingCenter::Khabarovsk,
            28 => OriginatingCenter::NewDelhi,
            29 => OriginatingCenter::NewDelhi,
            30 => OriginatingCenter::Novosibirsk,
            31 => OriginatingCenter::Novosibirsk,
            32 => OriginatingCenter::Tashkent,
            33 => OriginatingCenter::Jeddah,
            34 => OriginatingCenter::TokyoJapaneseMeteorologicalAgency,
            35 => OriginatingCenter::TokyoJapaneseMeteorologicalAgency,
            36 => OriginatingCenter::Bankok,
            37 => OriginatingCenter::UlanBator,
            38 => OriginatingCenter::Beijing,
            39 => OriginatingCenter::Beijing,
            40 => OriginatingCenter::Seoul,
            41 => OriginatingCenter::BuenosAires,
            42 => OriginatingCenter::BuenosAires,
            43 => OriginatingCenter::Brasilia,
            44 => OriginatingCenter::Brasilia,
            45 => OriginatingCenter::Santiago,
            46 => OriginatingCenter::BrazilianSpaceAgencyInpe,
            47 => OriginatingCenter::Columbia,
            48 => OriginatingCenter::Ecuador,
            49 => OriginatingCenter::Peru,
            50 => OriginatingCenter::Venezuela,
            51 => OriginatingCenter::Miami,
            52 => OriginatingCenter::MiamiNationalHurricaneCenter,
            53 => OriginatingCenter::CanadianMeteorologicalServiceMontreal,
            54 => OriginatingCenter::CanadianMeteorologicalServiceMontreal,
            55 => OriginatingCenter::SanFrancisco,
            56 => OriginatingCenter::ArincCenter,
            57 => OriginatingCenter::UsAirForceAirForceGlobalWeatherCenter,
            58 => OriginatingCenter::FleetNumericalMeteorologyAndOceanographyCenter,
            59 => OriginatingCenter::TheNoaaForecastSystemsLab,
            60 => OriginatingCenter::NationalCenterForAtmosphericResearch,
            61 => OriginatingCenter::ServiceArgosLandover,
            62 => OriginatingCenter::UsNavalOceanographicOffice,
            63 => OriginatingCenter::InternationalResearchInstitudeForClimateAndSociety,
            64 => OriginatingCenter::Honolulu,
            65 => OriginatingCenter::Darwin,
            66 => OriginatingCenter::Darwin,
            67 => OriginatingCenter::Melbourne,
            68 => OriginatingCenter::Reserved,
            69 => OriginatingCenter::Wellington,
            70 => OriginatingCenter::Wellington,
            71 => OriginatingCenter::Nadi,
            72 => OriginatingCenter::Singapore,
            73 => OriginatingCenter::Malaysia,
            74 => OriginatingCenter::UKMetOfficeExeter,
            75 => OriginatingCenter::UKMetOfficeExeter,
            76 => OriginatingCenter::Moscow,
            77 => OriginatingCenter::Reserved,
            78 => OriginatingCenter::Offenbach,
            79 => OriginatingCenter::Offenbach,
            80 => OriginatingCenter::Rome,
            81 => OriginatingCenter::Rome,
            82 => OriginatingCenter::Norrkoping,
            83 => OriginatingCenter::Norrkoping,
            84 => OriginatingCenter::FrenchWeatherServiceToulouse,
            85 => OriginatingCenter::FrenchWeatherServiceToulouse,
            86 => OriginatingCenter::Helsinki,
            87 => OriginatingCenter::Belgrade,
            88 => OriginatingCenter::Oslo,
            89 => OriginatingCenter::Prague,
            90 => OriginatingCenter::Episkopi,
            91 => OriginatingCenter::Ankara,
            92 => OriginatingCenter::FrankfurtMain,
            93 => OriginatingCenter::London,
            94 => OriginatingCenter::Copenhagen,
            95 => OriginatingCenter::Rota,
            96 => OriginatingCenter::Athens,
            97 => OriginatingCenter::EuropeanSpaceAgency,
            98 => OriginatingCenter::EuropeanCenterForMediumRangeWeatherForecasts,
            99 => OriginatingCenter::DeBiltNetherlands,
            100 => OriginatingCenter::Brazzaville,
            101 => OriginatingCenter::Abidjan,
            102 => OriginatingCenter::LibyanArabJamahiriya,
            103 => OriginatingCenter::Madagascar,
            104 => OriginatingCenter::Mauritius,
            105 => OriginatingCenter::Niger,
            106 => OriginatingCenter::Seychelles,
            107 => OriginatingCenter::Uganda,
            108 => OriginatingCenter::UnitedRepublicOfTanzania,
            109 => OriginatingCenter::Zimbabwe,
            110 => OriginatingCenter::HongKong,
            111 => OriginatingCenter::Afghanistan,
            112 => OriginatingCenter::Bahrain,
            113 => OriginatingCenter::Bangladesh,
            114 => OriginatingCenter::Bhutan,
            115 => OriginatingCenter::Cambodia,
            116 => OriginatingCenter::DemocraticPeoplesRepublicOfKorea,
            117 => OriginatingCenter::IslamicRepublicOfIran,
            118 => OriginatingCenter::Iraq,
            119 => OriginatingCenter::Kazakhstan,
            120 => OriginatingCenter::Kuwait,
            121 => OriginatingCenter::KyrgyzRepublic,
            122 => OriginatingCenter::LaoPeopleSDemocraticRepublic,
            123 => OriginatingCenter::MacaoChina,
            124 => OriginatingCenter::Maldives,
            125 => OriginatingCenter::Myanmar,
            126 => OriginatingCenter::Nepal,
            127 => OriginatingCenter::Oman,
            128 => OriginatingCenter::Pakistan,
            129 => OriginatingCenter::Qatar,
            130 => OriginatingCenter::Yemen,
            131 => OriginatingCenter::SriLanka,
            132 => OriginatingCenter::Tajikistan,
            133 => OriginatingCenter::Turkmenistan,
            134 => OriginatingCenter::UnitedArabEmirates,
            135 => OriginatingCenter::Uzbekistan,
            136 => OriginatingCenter::VietNam,
            137..=139 => OriginatingCenter::Reserved,
            140 => OriginatingCenter::Bolivia,
            141 => OriginatingCenter::Guyana,
            142 => OriginatingCenter::Paraguay,
            143 => OriginatingCenter::Suriname,
            144 => OriginatingCenter::Uruguay,
            145 => OriginatingCenter::FrenchGuyana,
            146 => OriginatingCenter::BrazilianNavyHydrographicCenter,
            147 => OriginatingCenter::NationalCommissionOnSpaceActivitiesArgentina,
            148 => OriginatingCenter::BrazilianDepartmentOfAirspaceControlDecea,
            149 => OriginatingCenter::Reserved,
            150 => OriginatingCenter::AntiguaAndBarbuda,
            151 => OriginatingCenter::Bahamas,
            152 => OriginatingCenter::Barbados,
            153 => OriginatingCenter::Belize,
            154 => OriginatingCenter::BritishCaribbeanTerritoriesCenter,
            155 => OriginatingCenter::SanJose,
            156 => OriginatingCenter::Cuba,
            157 => OriginatingCenter::Dominica,
            158 => OriginatingCenter::DominicanRepublic,
            159 => OriginatingCenter::ElSalvador,
            160 => OriginatingCenter::UsNoaaNesdis,
            161 => OriginatingCenter::UsNoaaOfficeOfOceanicAndAtmosphericResearch,
            162 => OriginatingCenter::Guatemala,
            163 => OriginatingCenter::Haiti,
            164 => OriginatingCenter::Honduras,
            165 => OriginatingCenter::Jamaica,
            166 => OriginatingCenter::MexicoCity,
            167 => OriginatingCenter::NetherlandsAntillesAndAruba,
            168 => OriginatingCenter::Nicaragua,
            169 => OriginatingCenter::Panama,
            170 => OriginatingCenter::SaintLucia,
            171 => OriginatingCenter::TrinidadAndTobago,
            172 => OriginatingCenter::FrenchDepartmentsInRaIv,
            173 => OriginatingCenter::UsNationalAeronauticsAndSpaceAdministration,
            174 => OriginatingCenter::IntegratedSystemDataManagementMarineEnvironmentalDataServiceCanada,
            175 => OriginatingCenter::Reserved,
            176 => OriginatingCenter::UsCooperativeInstitudeForMeteorologicalSatelliteStudies,
            177..=189 => OriginatingCenter::Reserved,
            190 => OriginatingCenter::CookIslands,
            191 => OriginatingCenter::FrenchPolynesia,
            192 => OriginatingCenter::Tonga,
            193 => OriginatingCenter::Vanuatu,
            194 => OriginatingCenter::Brunei,
            195 => OriginatingCenter::Indonesia,
            196 => OriginatingCenter::Kiribati,
            197 => OriginatingCenter::FederatedStatesOfMicronesia,
            198 => OriginatingCenter::NewCaledonia,
            199 => OriginatingCenter::Niue,
            200 => OriginatingCenter::PapuaNewGuinea,
            201 => OriginatingCenter::Philippines,
            202 => OriginatingCenter::Samoa,
            203 => OriginatingCenter::SolomonIslands,
            204 => OriginatingCenter::NationalInstitudeOfWaterAndAtmosphericResearchNewZealand,
            205..=209 => OriginatingCenter::Reserved,
            210 => OriginatingCenter::Frascati,
            211 => OriginatingCenter::Lanion,
            212 => OriginatingCenter::Lisbon,
            213 => OriginatingCenter::Reykjavik,
            214 => OriginatingCenter::Madrid,
            215 => OriginatingCenter::Zurich,
            216 => OriginatingCenter::ServiceArgosToulouse,
            217 => OriginatingCenter::Bratislava,
            218 => OriginatingCenter::Budapest,
            219 => OriginatingCenter::Ljubljana,
            220 => OriginatingCenter::Warsaw,
            221 => OriginatingCenter::Zagreb,
            222 => OriginatingCenter::Albania,
            223 => OriginatingCenter::Armenia,
            224 => OriginatingCenter::Austria,
            225 => OriginatingCenter::Azerbaijan,
            226 => OriginatingCenter::Belarus,
            227 => OriginatingCenter::Belgium,
            228 => OriginatingCenter::BosniaAndHerzegovina,
            229 => OriginatingCenter::Bulgaria,
            230 => OriginatingCenter::Cyprus,
            231 => OriginatingCenter::Estonia,
            232 => OriginatingCenter::Georgia,
            233 => OriginatingCenter::Dublin,
            234 => OriginatingCenter::Israel,
            235 => OriginatingCenter::Jordan,
            236 => OriginatingCenter::Latvia,
            237 => OriginatingCenter::Lebanon,
            238 => OriginatingCenter::Lithuania,
            239 => OriginatingCenter::Luxembourg,
            240 => OriginatingCenter::Malta,
            241 => OriginatingCenter::Monaco,
            242 => OriginatingCenter::Romania,
            243 => OriginatingCenter::SyrianArabRepublic,
            244 => OriginatingCenter::TheFormerYugoslavRepublicOfMacedonia,
            245 => OriginatingCenter::Ukraine,
            246 => OriginatingCenter::RepublicOfMoldova,
            247 => OriginatingCenter::OperationalProgrammeForTheExchangeOfWeatherRadarInformationEumetnet,
            248..=249 => OriginatingCenter::Reserved,
            250 => OriginatingCenter::ConsortiumForSmallScaleModelling,
            251..=253 => OriginatingCenter::Reserved,
            254 => OriginatingCenter::EumetsatOperationsCenter,
            _ => OriginatingCenter::MissingValue,
        }
    }
}
