use serde::{Deserialize, Serialize};

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub enum OriginatingCenter {
    Melbourne,
    Moscow,
    UsNationalWeatherServiceNcep,
    UsNationalWeatherServiceNwstg,
    UsNationalWeatherServiceOther,
    Cairo,
    Dakar,
    Nairobi,
    Casablanca,
    Tunis,
    TunisCasablanca,
    LasPalmas,
    Algiers,
    Acmad,
    Mozambique,
    Pretoria,
    LaReunion,
    Khabarovsk,
    NewDelhi,
    Novosibirsk,
    Tashkent,
    Jeddah,
    TokyoJapaneseMeteorologicalAgency,
    Bankok,
    UlanBator,
    Beijing,
    Seoul,
    BuenosAires,
    Brasilia,
    Santiago,
    BrazilianSpaceAgencyInpe,
    Columbia,
    Ecuador,
    Peru,
    Venezuela,
    Miami,
    MiamiNationalHurricaneCenter,
    CanadianMeteorologicalServiceMontreal,
    SanFrancisco,
    ArincCenter,
    UsAirForceAirForceGlobalWeatherCenter,
    FleetNumericalMeteorologyAndOceanographyCenter,
    TheNoaaForecastSystemsLab,
    NationalCenterForAtmosphericResearch,
    ServiceArgosLandover,
    UsNavalOceanographicOffice,
    InternationalResearchInstitudeForClimateAndSociety,
    Honolulu,
    Darwin,
    Reserved,
    Wellington,
    Nadi,
    Singapore,
    Malaysia,
    UKMetOfficeExeter,
    Offenbach,
    Rome,
    Norrkoping,
    FrenchWeatherServiceToulouse,
    Helsinki,
    Belgrade,
    Oslo,
    Prague,
    Episkopi,
    Ankara,
    FrankfurtMain,
    London,
    Copenhagen,
    Rota,
    Athens,
    EuropeanSpaceAgency,
    EuropeanCenterForMediumRangeWeatherForecasts,
    DeBiltNetherlands,
    Brazzaville,
    Abidjan,
    LibyanArabJamahiriya,
    Madagascar,
    Mauritius,
    Niger,
    Seychelles,
    Uganda,
    UnitedRepublicOfTanzania,
    Zimbabwe,
    HongKong,
    Afghanistan,
    Bahrain,
    Bangladesh,
    Bhutan,
    Cambodia,
    DemocraticPeoplesRepublicOfKorea,
    IslamicRepublicOfIran,
    Iraq,
    Kazakhstan,
    Kuwait,
    KyrgyzRepublic,
    LaoPeopleSDemocraticRepublic,
    MacaoChina,
    Maldives,
    Myanmar,
    Nepal,
    Oman,
    Pakistan,
    Qatar,
    Yemen,
    SriLanka,
    Tajikistan,
    Turkmenistan,
    UnitedArabEmirates,
    Uzbekistan,
    VietNam,
    Bolivia,
    Guyana,
    Paraguay,
    Suriname,
    Uruguay,
    FrenchGuyana,
    BrazilianNavyHydrographicCenter,
    NationalCommissionOnSpaceActivitiesArgentina,
    BrazilianDepartmentOfAirspaceControlDecea,
    AntiguaAndBarbuda,
    Bahamas,
    Barbados,
    Belize,
    BritishCaribbeanTerritoriesCenter,
    SanJose,
    Cuba,
    Dominica,
    DominicanRepublic,
    ElSalvador,
    UsNoaaNesdis,
    UsNoaaOfficeOfOceanicAndAtmosphericResearch,
    Guatemala,
    Haiti,
    Honduras,
    Jamaica,
    MexicoCity,
    NetherlandsAntillesAndAruba,
    Nicaragua,
    Panama,
    SaintLucia,
    TrinidadAndTobago,
    FrenchDepartmentsInRaIv,
    UsNationalAeronauticsAndSpaceAdministration,
    IntegratedSystemDataManagementMarineEnvironmentalDataServiceCanada,
    UsCooperativeInstitudeForMeteorologicalSatelliteStudies,
    CookIslands,
    FrenchPolynesia,
    Tonga,
    Vanuatu,
    Brunei,
    Indonesia,
    Kiribati,
    FederatedStatesOfMicronesia,
    NewCaledonia,
    Niue,
    PapuaNewGuinea,
    Philippines,
    Samoa,
    SolomonIslands,
    NationalInstitudeOfWaterAndAtmosphericResearchNewZealand,
    Frascati,
    Lanion,
    Lisbon,
    Reykjavik,
    Madrid,
    Zurich,
    ServiceArgosToulouse,
    Bratislava,
    Budapest,
    Ljubljana,
    Warsaw,
    Zagreb,
    Albania,
    Armenia,
    Austria,
    Azerbaijan,
    Belarus,
    Belgium,
    BosniaAndHerzegovina,
    Bulgaria,
    Cyprus,
    Estonia,
    Georgia,
    Dublin,
    Israel,
    Jordan,
    Latvia,
    Lebanon,
    Lithuania,
    Luxembourg,
    Malta,
    Monaco,
    Romania,
    SyrianArabRepublic,
    TheFormerYugoslavRepublicOfMacedonia,
    Ukraine,
    RepublicOfMoldova,
    OperationalProgrammeForTheExchangeOfWeatherRadarInformationEumetnet,
    ConsortiumForSmallScaleModelling,
    EumetsatOperationsCenter,
    MissingValue,
}

impl From<u16> for OriginatingCenter {
    fn from(n: u16) -> Self {
        match n {
            01 => Self::Melbourne,
            02 => Self::Melbourne,
            03 => Self::Melbourne,
            04 => Self::Moscow,
            05 => Self::Moscow,
            06 => Self::Moscow,
            07 => Self::UsNationalWeatherServiceNcep,
            08 => Self::UsNationalWeatherServiceNwstg,
            09 => Self::UsNationalWeatherServiceOther,
            10 => Self::Cairo,
            11 => Self::Cairo,
            12 => Self::Dakar,
            13 => Self::Dakar,
            14 => Self::Nairobi,
            15 => Self::Nairobi,
            16 => Self::Casablanca,
            17 => Self::Tunis,
            18 => Self::TunisCasablanca,
            19 => Self::TunisCasablanca,
            20 => Self::LasPalmas,
            21 => Self::Algiers,
            22 => Self::Acmad,
            23 => Self::Mozambique,
            24 => Self::Pretoria,
            25 => Self::LaReunion,
            26 => Self::Khabarovsk,
            27 => Self::Khabarovsk,
            28 => Self::NewDelhi,
            29 => Self::NewDelhi,
            30 => Self::Novosibirsk,
            31 => Self::Novosibirsk,
            32 => Self::Tashkent,
            33 => Self::Jeddah,
            34 => Self::TokyoJapaneseMeteorologicalAgency,
            35 => Self::TokyoJapaneseMeteorologicalAgency,
            36 => Self::Bankok,
            37 => Self::UlanBator,
            38 => Self::Beijing,
            39 => Self::Beijing,
            40 => Self::Seoul,
            41 => Self::BuenosAires,
            42 => Self::BuenosAires,
            43 => Self::Brasilia,
            44 => Self::Brasilia,
            45 => Self::Santiago,
            46 => Self::BrazilianSpaceAgencyInpe,
            47 => Self::Columbia,
            48 => Self::Ecuador,
            49 => Self::Peru,
            50 => Self::Venezuela,
            51 => Self::Miami,
            52 => Self::MiamiNationalHurricaneCenter,
            53 => Self::CanadianMeteorologicalServiceMontreal,
            54 => Self::CanadianMeteorologicalServiceMontreal,
            55 => Self::SanFrancisco,
            56 => Self::ArincCenter,
            57 => Self::UsAirForceAirForceGlobalWeatherCenter,
            58 => Self::FleetNumericalMeteorologyAndOceanographyCenter,
            59 => Self::TheNoaaForecastSystemsLab,
            60 => Self::NationalCenterForAtmosphericResearch,
            61 => Self::ServiceArgosLandover,
            62 => Self::UsNavalOceanographicOffice,
            63 => Self::InternationalResearchInstitudeForClimateAndSociety,
            64 => Self::Honolulu,
            65 => Self::Darwin,
            66 => Self::Darwin,
            67 => Self::Melbourne,
            68 => Self::Reserved,
            69 => Self::Wellington,
            70 => Self::Wellington,
            71 => Self::Nadi,
            72 => Self::Singapore,
            73 => Self::Malaysia,
            74 => Self::UKMetOfficeExeter,
            75 => Self::UKMetOfficeExeter,
            76 => Self::Moscow,
            77 => Self::Reserved,
            78 => Self::Offenbach,
            79 => Self::Offenbach,
            80 => Self::Rome,
            81 => Self::Rome,
            82 => Self::Norrkoping,
            83 => Self::Norrkoping,
            84 => Self::FrenchWeatherServiceToulouse,
            85 => Self::FrenchWeatherServiceToulouse,
            86 => Self::Helsinki,
            87 => Self::Belgrade,
            88 => Self::Oslo,
            89 => Self::Prague,
            90 => Self::Episkopi,
            91 => Self::Ankara,
            92 => Self::FrankfurtMain,
            93 => Self::London,
            94 => Self::Copenhagen,
            95 => Self::Rota,
            96 => Self::Athens,
            97 => Self::EuropeanSpaceAgency,
            98 => Self::EuropeanCenterForMediumRangeWeatherForecasts,
            99 => Self::DeBiltNetherlands,
            100 => Self::Brazzaville,
            101 => Self::Abidjan,
            102 => Self::LibyanArabJamahiriya,
            103 => Self::Madagascar,
            104 => Self::Mauritius,
            105 => Self::Niger,
            106 => Self::Seychelles,
            107 => Self::Uganda,
            108 => Self::UnitedRepublicOfTanzania,
            109 => Self::Zimbabwe,
            110 => Self::HongKong,
            111 => Self::Afghanistan,
            112 => Self::Bahrain,
            113 => Self::Bangladesh,
            114 => Self::Bhutan,
            115 => Self::Cambodia,
            116 => Self::DemocraticPeoplesRepublicOfKorea,
            117 => Self::IslamicRepublicOfIran,
            118 => Self::Iraq,
            119 => Self::Kazakhstan,
            120 => Self::Kuwait,
            121 => Self::KyrgyzRepublic,
            122 => Self::LaoPeopleSDemocraticRepublic,
            123 => Self::MacaoChina,
            124 => Self::Maldives,
            125 => Self::Myanmar,
            126 => Self::Nepal,
            127 => Self::Oman,
            128 => Self::Pakistan,
            129 => Self::Qatar,
            130 => Self::Yemen,
            131 => Self::SriLanka,
            132 => Self::Tajikistan,
            133 => Self::Turkmenistan,
            134 => Self::UnitedArabEmirates,
            135 => Self::Uzbekistan,
            136 => Self::VietNam,
            137..=139 => Self::Reserved,
            140 => Self::Bolivia,
            141 => Self::Guyana,
            142 => Self::Paraguay,
            143 => Self::Suriname,
            144 => Self::Uruguay,
            145 => Self::FrenchGuyana,
            146 => Self::BrazilianNavyHydrographicCenter,
            147 => Self::NationalCommissionOnSpaceActivitiesArgentina,
            148 => Self::BrazilianDepartmentOfAirspaceControlDecea,
            149 => Self::Reserved,
            150 => Self::AntiguaAndBarbuda,
            151 => Self::Bahamas,
            152 => Self::Barbados,
            153 => Self::Belize,
            154 => Self::BritishCaribbeanTerritoriesCenter,
            155 => Self::SanJose,
            156 => Self::Cuba,
            157 => Self::Dominica,
            158 => Self::DominicanRepublic,
            159 => Self::ElSalvador,
            160 => Self::UsNoaaNesdis,
            161 => Self::UsNoaaOfficeOfOceanicAndAtmosphericResearch,
            162 => Self::Guatemala,
            163 => Self::Haiti,
            164 => Self::Honduras,
            165 => Self::Jamaica,
            166 => Self::MexicoCity,
            167 => Self::NetherlandsAntillesAndAruba,
            168 => Self::Nicaragua,
            169 => Self::Panama,
            170 => Self::SaintLucia,
            171 => Self::TrinidadAndTobago,
            172 => Self::FrenchDepartmentsInRaIv,
            173 => Self::UsNationalAeronauticsAndSpaceAdministration,
            174 => Self::IntegratedSystemDataManagementMarineEnvironmentalDataServiceCanada,
            175 => Self::Reserved,
            176 => Self::UsCooperativeInstitudeForMeteorologicalSatelliteStudies,
            177..=189 => Self::Reserved,
            190 => Self::CookIslands,
            191 => Self::FrenchPolynesia,
            192 => Self::Tonga,
            193 => Self::Vanuatu,
            194 => Self::Brunei,
            195 => Self::Indonesia,
            196 => Self::Kiribati,
            197 => Self::FederatedStatesOfMicronesia,
            198 => Self::NewCaledonia,
            199 => Self::Niue,
            200 => Self::PapuaNewGuinea,
            201 => Self::Philippines,
            202 => Self::Samoa,
            203 => Self::SolomonIslands,
            204 => Self::NationalInstitudeOfWaterAndAtmosphericResearchNewZealand,
            205..=209 => Self::Reserved,
            210 => Self::Frascati,
            211 => Self::Lanion,
            212 => Self::Lisbon,
            213 => Self::Reykjavik,
            214 => Self::Madrid,
            215 => Self::Zurich,
            216 => Self::ServiceArgosToulouse,
            217 => Self::Bratislava,
            218 => Self::Budapest,
            219 => Self::Ljubljana,
            220 => Self::Warsaw,
            221 => Self::Zagreb,
            222 => Self::Albania,
            223 => Self::Armenia,
            224 => Self::Austria,
            225 => Self::Azerbaijan,
            226 => Self::Belarus,
            227 => Self::Belgium,
            228 => Self::BosniaAndHerzegovina,
            229 => Self::Bulgaria,
            230 => Self::Cyprus,
            231 => Self::Estonia,
            232 => Self::Georgia,
            233 => Self::Dublin,
            234 => Self::Israel,
            235 => Self::Jordan,
            236 => Self::Latvia,
            237 => Self::Lebanon,
            238 => Self::Lithuania,
            239 => Self::Luxembourg,
            240 => Self::Malta,
            241 => Self::Monaco,
            242 => Self::Romania,
            243 => Self::SyrianArabRepublic,
            244 => Self::TheFormerYugoslavRepublicOfMacedonia,
            245 => Self::Ukraine,
            246 => Self::RepublicOfMoldova,
            247 => Self::OperationalProgrammeForTheExchangeOfWeatherRadarInformationEumetnet,
            248..=249 => Self::Reserved,
            250 => Self::ConsortiumForSmallScaleModelling,
            251..=253 => Self::Reserved,
            254 => Self::EumetsatOperationsCenter,
            _ => Self::MissingValue,
        }
    }
}
